### PR TITLE
Fix nesteddict2yaml not to fumble empty dict values

### PR DESCRIPTION
**Pull request by sakurai-youhei**
See also:
- https://github.com/cr0hn/aiohttp-swagger/pull/107
- https://github.com/cr0hn/aiohttp-swagger/issues/106

### CODE REVIEW

**Comment by sakurai-youhei** [comment]
@stj Could you consider merging this PR and tagging? Thank you.

**Comment by stj** [comment]
@sakurai-youhei the upstream project is dead. It says it looks for maintainers. It hasn't had an update in 3 years I believe.
Opening issues upstream might not be worth a lot.

**Review by stj — COMMENTED** [review]
So an empty dict becomes nothing in yaml?
Is the result accurate if you do a JSON to YAML to JSON conversion?
I expect to see `{}` in the YAML, but this change will result in an empty dict being `None`, right?
@sakurai-youhei

**Comment by sakurai-youhei** [comment]
@stj Yeah, I had a faint hope that if I sent a PR, it might be taken in, but looking at the current situation, it seems that there is no possibility of a revival.

> So an empty dict becomes nothing in yaml?

Yes. I believe that is inpreferable behavior addressed in this PR.

**Current behavior**

Definition:
```python
definitions = dict(
    test={
        "type": "object",
        "properties": {"prop": {"type": "object", "default": dict()}},
    }
)
```

JSON:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Swagger API",
    "description": "Swagger API definition",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/"
    }
  ],
  "components": {
    "schemas": {
      "test": {
        "type": "object",
        "properties": {
          "prop": {
            "type": "object",
            "default": null
          }
        }
      }
    }
  },
  "paths": {}
}
```

YAML:
```yaml
openapi: 3.0.1
info:
  title: Swagger API
  description: Swagger API definition
  version: 1.0.0
servers:
- url: "/"
components:
  schemas:
    test:
      type: object
      properties:
        prop:
          type: object
          default: 
paths: {}
```

**Expected behavior**

Definition: Same

JSON:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Swagger API",
    "description": "Swagger API definition",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/"
    }
  ],
  "components": {
    "schemas": {
      "test": {
        "type": "object",
        "properties": {
          "prop": {
            "type": "object",
            "default": {}
          }
        }
      }
    }
  },
  "paths": {}
}
```

YAML:
```yaml
openapi: 3.0.1
info:
  title: Swagger API
  description: Swagger API definition
  version: 1.0.0
servers:
- url: "/"
components:
  schemas:
    test:
      type: object
      properties:
        prop:
          type: object
          default: {}
paths: {}
```

> Is the result accurate if you do a JSON to YAML to JSON conversion?

Yes.

> I expect to see {} in the YAML, but this change will result in an empty dict being None, right?

I have the same expectation as yours. So this change will correct the current behavior to be aligned to our expectation - an empty dict being not None but `{}`.

**Pull request merged**
